version: '3'
services:
  medicare-mysql:
    image: mysql:8.0.18
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./medicaredb:/var/lib/mysql
      - ./micro-services/dbscripts:/docker-entrypoint-initdb.d
      
  eureka-discovery-server:
    image: eureka-discovery-server-app
    build: micro-services/eureka-discovery-server/.
    ports:
      - 8761:8761
      
  zuul-gateway:
    image: zuul-gateway-server-app
    build: ./micro-services/zuul-gateway/.
    ports:
      - 8083:8083
  
  signup-service:
    image: signup-service-app
    build: ./micro-services/signup-service/.
    ports:
      - 8093:8093
    depends_on:
      - medicare-mysql
      - eureka-discovery-server
    links:
      - medicare-mysql
      - eureka-discovery-server
  
  medicare-center-service:
    image: medicare-center-service-app
    build: ./micro-services/medicare-center/.
    ports:
      - 8092:8092
    depends_on:
      - medicare-mysql
      - eureka-discovery-server
    links:
      - medicare-mysql
      - eureka-discovery-server
  
  medicare-webapp:
    image: medicare-webapp-app
    build: ./medicare-webapp/.
    ports:
      - 8090:80 
  
  authentication-service:
    image: authentication-app
    build: ./micro-services/authentication/.
    ports:
      - 8091:8091
    depends_on:
      - medicare-mysql
      - eureka-discovery-server
    links:
      - medicare-mysql
      - eureka-discovery-server